name: schema-registry-sdk-go
lang: go
git:
  enable: true
  hook:
    enable: true
github:
  enable: true
gitignore:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  tasks:
    - name: create-git-tag
      branch: main
      pipeline_file: .semaphore/create-git-tag.yml
      parameters:
        - name: TAG_NAME
          required: true
          description: The name of the tag to be created.
          default_value: "X.Y.Z"
